### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by loaferer** [Lodour/Weibo-Album-Crawler#3]
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/xuxingwang/Downloads/Weibo-Album-Crawler-master/Weibo-Album-Crawler-master/weibo.py
Traceback (most recent call last):
  File "/Users/xuxingwang/Downloads/Weibo-Album-Crawler-master/Weibo-Album-Crawler-master/weibo.py", line 8, in <module>
    from settings import *
  File "/Users/xuxingwang/Downloads/Weibo-Album-Crawler-master/Weibo-Album-Crawler-master/settings.py", line 3, in <module>
    from colorama import init
ModuleNotFoundError: No module named 'colorama'

Process finished with exit code 1

**Comment by Lodour** [comment]
要按照Usage里的步骤安装venv和相关依赖
> virtualenv env --python=python3.5
> source ./env/bin/activate
> pip install -r requirements.txt

**Comment by loaferer** [comment]
成功了，谢谢
