### ISSUE TITLE
运行一段时间报错

### ISSUE THREAD

**Issue by H273** [Lodour/Weibo-Album-Crawler#4]
运行一段时间报错，《面孔专辑》相册下载不全，《微博配图》无法下载。
报错信息如下，请协助排查原因，多谢！作者辛苦
Traceback (most recent call last):
  File "weibo.py", line 269, in <module>
    run(t)
  File "weibo.py", line 262, in run
    down_album(album)
  File "weibo.py", line 227, in down_album
    large_photos = get_large_photos(album, ids)
  File "weibo.py", line 143, in get_large_photos
    url=data[i]['large_pic_tmp']))
KeyError: 'large_pic_tmp'

环境：
Windows 7 64bit 企业版
Python 3.6.2

环境：
Windows 7 64bit 企业版
Python 3.6.2

**Comment by Lodour** [comment]
是所有用户都这样吗，还是个例？
如果是个例能否提供一下用户id？

**Comment by H273** [comment]
所有用户都这样，所有《微博配图》相册文件夹都没新建出来，运行环境就是上面提供的，辛苦作者排查原因
